"""Freeze the package inventory and SHA256 checksum ledger."""

from __future__ import annotations

import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "REPRODUCIBILITY_MANIFEST.json"
CHECKSUMS = ROOT / "CHECKSUMS_SHA256.txt"
CONTROL_FILES = {MANIFEST.name, CHECKSUMS.name}


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def category(relative: str) -> str:
    top = relative.split("/", 1)[0]
    return {
        "data": "dataset",
        "src": "source_code",
        "configs": "configuration",
        "models": "model",
        "scripts": "reproduction_code",
        "results": "result_or_evidence",
        "trajectories": "trajectory",
        "tables": "table",
        "figures": "figure",
        "docs": "documentation",
        "tests": "test",
    }.get(top, "package_metadata")


def status(relative: str) -> str:
    if relative.startswith(("tables/", "figures/main/", "figures/supplementary/")):
        return "FINAL / AUTHORITATIVE"
    if relative.startswith(("results/authoritative/", "data/processed/", "models/")):
        return "FINAL / AUTHORITATIVE"
    if relative.startswith(("src/", "configs/", "scripts/", "trajectories/")):
        return "REQUIRED FOR REPRODUCTION"
    return "OPTIONAL SUPPORTING"


def role(relative: str) -> str:
    if relative.endswith("selected_validation_checkpoint.zip"):
        return "frozen selected validation checkpoint"
    if relative.startswith("results/reproduced/"):
        return "output independently regenerated by the frozen-model workflow"
    if relative.startswith("results/authoritative/SOURCE_TABLE_"):
        return "unaltered legacy source table retained for aggregation audit"
    if relative.startswith("tables/"):
        return "machine-readable final table with explicit aggregation labels"
    if relative.startswith("trajectories/"):
        return "daily-reset held-out trajectory used for independent metric replay"
    if relative.startswith("data/processed/scenarios/"):
        return "derived workload-scenario dataset"
    if relative.startswith("data/processed/"):
        return "processed publication benchmark dataset"
    if relative.startswith("figures/"):
        return "frozen manuscript figure or figure documentation"
    if relative.startswith("models/"):
        return "checkpoint metadata, configuration snapshot, or model inventory"
    if relative.startswith("scripts/reference/"):
        return "optional historical source-of-truth script"
    if relative.startswith("scripts/"):
        return "portable frozen-model reproduction workflow"
    if relative.startswith("src/"):
        return "final environment, controller, safety, data, or metric implementation"
    if relative.startswith("configs/"):
        return "portable final configuration or scenario definition"
    if relative.startswith("tests/"):
        return "final regression test"
    return "package documentation or environment metadata"


def source_original_path(relative: str) -> str:
    if relative.startswith("results/reproduced/") or relative in {
        "results/REPRODUCTION_VALIDATION.csv",
        "tables/TABLE_MAIN_CONTROLLER_RESULTS.csv",
        "tables/TABLE_IT_SCENARIO_RESULTS.csv",
        "tables/TABLE_TRUE_ABLATION_RESULTS.csv",
        "tables/TABLE_SAFETY_RESULTS.csv",
        "models/MODEL_MANIFEST.csv",
    }:
        return "generated within reproducibility package from frozen artifacts"
    if relative.startswith("data/processed/scenarios/"):
        return "vpp__final/results/publication_v1/scenarios/datasets"
    if relative.startswith("data/processed/"):
        return "vpp__final/results/publication_v1/dataset"
    if relative.startswith("data/metadata/"):
        return "vpp__final/results/publication_v1/dataset and repository documentation"
    if relative.startswith("src/"):
        return relative.removeprefix("src/")
    if relative.startswith("tests/"):
        return relative
    if relative.startswith("models/ablations/"):
        return "vpp__final/results/publication_v1/ablations/models"
    if relative.startswith("models/"):
        return "vpp__final/results/publication_v1/models"
    if relative.startswith("trajectories/baseline/"):
        return "vpp__final/results/publication_final/trajectories/deterministic_baselines"
    if relative.startswith("trajectories/learned_controllers/"):
        return "vpp__final/results/publication_v1/trajectories/daily_reset"
    if relative.startswith("trajectories/scenarios/"):
        return "vpp__final/results/publication_v1/scenarios/trajectories; corrected affected files from publication_final/scenario_trajectories"
    if relative.startswith("trajectories/ablations/"):
        return "vpp__final/results/publication_v1/ablations/trajectories"
    if relative.startswith("results/authoritative/"):
        return "vpp__final/results/publication_final/verification and final evidence"
    if relative.startswith("results/"):
        return "vpp__final/results/publication_final and publication_v1"
    if relative.startswith("figures/"):
        return "manuscript/submission_assets and manuscript/revised_assets"
    if relative.startswith("tables/"):
        return "vpp__final/results/publication_final/tables"
    if relative.startswith("scripts/reference/"):
        return "vpp__final/results/publication_final/scripts or repository scripts"
    if relative.startswith("configs/"):
        return "portable copy derived from final config snapshots; exact snapshots retained beside models"
    return "created specifically for reproducibility package"


def package_files() -> list[Path]:
    return sorted(
        path for path in ROOT.rglob("*")
        if path.is_file() and path.name not in CONTROL_FILES
    )


def main() -> None:
    records = []
    for path in package_files():
        relative = path.relative_to(ROOT).as_posix()
        records.append({
            "relative_path": relative,
            "category": category(relative),
            "role": role(relative),
            "file_size_bytes": path.stat().st_size,
            "sha256": sha256(path),
            "source_original_path": source_original_path(relative),
            "status": status(relative),
        })

    records.extend([
        {
            "relative_path": MANIFEST.name,
            "category": "package_metadata",
            "role": "self-describing artifact inventory",
            "file_size_bytes": None,
            "sha256": None,
            "source_original_path": "generated within reproducibility package",
            "status": "REQUIRED FOR REPRODUCTION",
            "checksum_note": "Self-hash is intentionally omitted; CHECKSUMS_SHA256.txt records this file.",
        },
        {
            "relative_path": CHECKSUMS.name,
            "category": "package_metadata",
            "role": "SHA256 ledger for every other packaged file",
            "file_size_bytes": None,
            "sha256": None,
            "source_original_path": "generated within reproducibility package",
            "status": "REQUIRED FOR REPRODUCTION",
            "checksum_note": "A checksum ledger cannot contain a stable checksum of itself.",
        },
    ])
    payload = {
        "schema_version": "1.0",
        "generated_utc": datetime.now(timezone.utc).isoformat(),
        "package_root": ROOT.name,
        "packaged_file_count": len(records),
        "self_reference_policy": (
            "The manifest lists both control files. Its own digest is stored in CHECKSUMS_SHA256.txt; "
            "the checksum ledger excludes only itself because a stable self-hash is impossible."
        ),
        "artifacts": records,
    }
    MANIFEST.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")

    checksum_lines = []
    for path in sorted(item for item in ROOT.rglob("*") if item.is_file() and item != CHECKSUMS):
        checksum_lines.append(f"{sha256(path)}  {path.relative_to(ROOT).as_posix()}")
    CHECKSUMS.write_text("\n".join(checksum_lines) + "\n", encoding="utf-8")
    print(json.dumps({
        "manifest_records": len(records),
        "checksummed_files": len(checksum_lines),
        "checksum_self_exclusion": CHECKSUMS.name,
    }, indent=2))


if __name__ == "__main__":
    main()
